/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Frames.Staff;

import DatabaseConenctor.MedicalHistory;
import DatabaseConenctor.Student;
import Frames.MainFrame;
import java.time.Instant;
import java.time.LocalDate;
import java.time.Period;
import java.time.ZoneId;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Date;
import java.util.List;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.persistence.PersistenceContext;
import javax.persistence.Query;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author netha
 */
public class StudentRecord extends javax.swing.JFrame {

    private Student student;
    private LocalDate localBirthDate;
    private int studentAge;
    private final DateTimeFormatter DOBFormat = DateTimeFormatter.ofPattern("MMMM dd, yyyy");
    private final DateTimeFormatter defaultDateFormat = DateTimeFormatter.ofPattern("MM/dd/yyyy");
    private MainFrame parentFrame;
    private MedicalHistory history;
    private DefaultTableModel allergiesTableModel;
    private DefaultTableModel medicationsTableModel;
    private DefaultTableModel hospitalizationTableModel;
    private List<String> allergies = new ArrayList<>();
    private List<String> medications = new ArrayList<>();
    private List<String> hospitalizations = new ArrayList<>();
    
    @PersistenceContext
    private EntityManager entityManager;
    @PersistenceContext
    private EntityManagerFactory entityManagerFactory;
    
    private Boolean isEnabled;
    private Date dateTaken;
    private boolean newRecord;

    public StudentRecord() {
        initComponents();
    }
    
    /**
     * Creates new form StudentRecord
     * @param parentFrame
     * @param student
     */
    public StudentRecord(MainFrame parentFrame, Student student) {
        this.parentFrame = parentFrame;
        this.entityManagerFactory = Persistence.createEntityManagerFactory("School_ClinicPU");
        this.entityManager = this.entityManagerFactory.createEntityManager();
        this.entityManager.getTransaction().begin();
        
        this.student = student;
        this.localBirthDate = this.student.getStudentBrithdate()
                .toInstant()
                .atZone(ZoneId.systemDefault())
                .toLocalDate();
        this.studentAge = Period.between(localBirthDate, LocalDate.now()).getYears();
        this.history = this.parentFrame.fetchMedicalHistory(this.student.getStudentID());
        this.dateTaken = Date.from(LocalDate.now().atStartOfDay(ZoneId.systemDefault()).toInstant());
        this.newRecord = this.history.getHistoryID() == null;
        
        initComponents();
        if (!this.newRecord) this.updateDisplay();
        this.enableComponents(this.newRecord);        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane2 = new javax.swing.JTabbedPane();
        dateChooser = new com.raven.datechooser.DateChooser();
        jLabel3 = new javax.swing.JLabel();
        dateCreated = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        recordScroll = new javax.swing.JScrollPane();
        recordPanel = new javax.swing.JPanel();
        hasHeartDiseas = new javax.swing.JCheckBox();
        hasAsthma = new javax.swing.JCheckBox();
        hasEpilipsy = new javax.swing.JCheckBox();
        hasHermia = new javax.swing.JCheckBox();
        jScrollPane3 = new javax.swing.JScrollPane();
        hospitalizationTable = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        allergiesTable = new javax.swing.JTable();
        addMedications = new javax.swing.JLabel();
        addAllergy = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        medicationsTable = new javax.swing.JTable();
        addHospitalized = new javax.swing.JLabel();
        femaleOnlyPanel = new javax.swing.JPanel();
        jLabel30 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        lmpDate = new com.toedter.calendar.JDateChooser();
        confirmRecord = new javax.swing.JButton();
        removeAllergy = new javax.swing.JLabel();
        removeHospitalization = new javax.swing.JLabel();
        removeMedication = new javax.swing.JLabel();
        reportPanel = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        historyPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel28 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();

        dateChooser.setDateFormat("MM/dd/yyyy");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(null);

        jLabel3.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("PATIENTS RECORD");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 10, 560, 40);

        dateCreated.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        dateCreated.setText(LocalDate.now().format(this.defaultDateFormat)
        );
        getContentPane().add(dateCreated);
        dateCreated.setBounds(50, 70, 70, 16);

        jLabel2.setText("Date:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 70, 40, 16);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText(this.localBirthDate.format(DOBFormat)
        );
        getContentPane().add(jLabel4);
        jLabel4.setBounds(80, 120, 170, 16);

        jLabel6.setText("Birthday:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(10, 120, 60, 16);

        jLabel7.setText("Name:");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(10, 100, 40, 16);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("%s %s. %s".formatted(this.student.getStudentFName(), this.student.getStudentMName().charAt(0), this.student.getStudentLName()));
        getContentPane().add(jLabel5);
        jLabel5.setBounds(80, 100, 230, 16);

        jLabel8.setText("Age:");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(10, 140, 30, 16);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setText(Integer.toString(this.studentAge));
        getContentPane().add(jLabel9);
        jLabel9.setBounds(80, 140, 40, 16);

        jLabel10.setText("Sex:");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(10, 160, 30, 16);

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel11.setText(this.student.getStudentSex().substring(0, 1).toUpperCase() + this.student.getStudentSex().substring(1)
        );
        getContentPane().add(jLabel11);
        jLabel11.setBounds(80, 160, 40, 16);

        jLabel12.setText("Civil Status:");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(10, 180, 70, 16);

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel13.setText(this.student.getStudentcivilStatus().equalsIgnoreCase("S") ? "Single" :
            this.student.getStudentcivilStatus().equalsIgnoreCase("M") ? "Married" :
            this.student.getStudentcivilStatus().equalsIgnoreCase("D") ? "Divorced" : "Widowed"
        );
        getContentPane().add(jLabel13);
        jLabel13.setBounds(80, 180, 60, 16);

        jLabel14.setText("Religion:");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(10, 200, 60, 16);

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel15.setText(this.student.getStudentReligion());
        getContentPane().add(jLabel15);
        jLabel15.setBounds(80, 200, 110, 16);

        jTabbedPane1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTabbedPane1.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);
        jTabbedPane1.setTabPlacement(javax.swing.JTabbedPane.LEFT);

        recordScroll.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        recordPanel.setEnabled(false);
        recordPanel.setPreferredSize(new java.awt.Dimension(489, 600));
        recordPanel.setLayout(null);

        hasHeartDiseas.setText("Heart Disease");
        recordPanel.add(hasHeartDiseas);
        hasHeartDiseas.setBounds(360, 20, 100, 20);

        hasAsthma.setText("Asthma");
        hasAsthma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hasAsthmaActionPerformed(evt);
            }
        });
        recordPanel.add(hasAsthma);
        hasAsthma.setBounds(20, 20, 64, 20);

        hasEpilipsy.setText("Epilepsy");
        recordPanel.add(hasEpilipsy);
        hasEpilipsy.setBounds(130, 20, 85, 20);

        hasHermia.setText("Hernia");
        recordPanel.add(hasHermia);
        hasHermia.setBounds(250, 20, 85, 20);

        jScrollPane3.setBorder(null);
        jScrollPane3.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        hospitalizationTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {""}
            },
            new String [] {
                "Hospitalizations"
            }
        ));
        hospitalizationTable.setShowHorizontalLines(true);
        jScrollPane3.setViewportView(hospitalizationTable);
        this.hospitalizationTableModel = (DefaultTableModel) this.hospitalizationTable.getModel();

        recordPanel.add(jScrollPane3);
        jScrollPane3.setBounds(20, 330, 450, 80);

        jScrollPane2.setBorder(null);
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        allergiesTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {""}
            },
            new String [] {
                "Allergies"
            }
        ));
        allergiesTable.setShowHorizontalLines(true);
        jScrollPane2.setViewportView(allergiesTable);
        this.allergiesTableModel = (DefaultTableModel) this.allergiesTable.getModel();

        recordPanel.add(jScrollPane2);
        jScrollPane2.setBounds(20, 90, 450, 80);

        addMedications.setText("+");
        addMedications.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addMedications.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addMedicationsMouseClicked(evt);
            }
        });
        recordPanel.add(addMedications);
        addMedications.setBounds(460, 190, 10, 16);

        addAllergy.setText("+");
        addAllergy.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addAllergy.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addAllergyMouseClicked(evt);
            }
        });
        recordPanel.add(addAllergy);
        addAllergy.setBounds(460, 70, 10, 16);

        jScrollPane4.setBorder(null);
        jScrollPane4.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        medicationsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {""}
            },
            new String [] {
                "Medicaitons"
            }
        ));
        medicationsTable.setShowHorizontalLines(true);
        jScrollPane4.setViewportView(medicationsTable);
        this.medicationsTableModel = (DefaultTableModel) this.medicationsTable.getModel();

        recordPanel.add(jScrollPane4);
        jScrollPane4.setBounds(20, 210, 450, 80);

        addHospitalized.setText("+");
        addHospitalized.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addHospitalizedMouseClicked(evt);
            }
        });
        recordPanel.add(addHospitalized);
        addHospitalized.setBounds(460, 310, 10, 16);

        femaleOnlyPanel.setLayout(null);

        jLabel30.setText("1st day of last menstrual period (LMP):");
        femaleOnlyPanel.add(jLabel30);
        jLabel30.setBounds(20, 40, 210, 20);

        jLabel29.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 51, 51));
        jLabel29.setText("<html>* <u>FOR FEMALE ONLY</>");
        femaleOnlyPanel.add(jLabel29);
        jLabel29.setBounds(10, 20, 110, 16);

        lmpDate.setDateFormatString("MM/dd/yyyy");
        femaleOnlyPanel.add(lmpDate);
        lmpDate.setBounds(238, 40, 210, 22);
        this.lmpDate.setEnabled(this.student.getStudentSex().equalsIgnoreCase("female"));

        recordPanel.add(femaleOnlyPanel);
        femaleOnlyPanel.setBounds(10, 420, 470, 90);

        confirmRecord.setText("Confirm");
        confirmRecord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmRecordActionPerformed(evt);
            }
        });
        recordPanel.add(confirmRecord);
        confirmRecord.setBounds(210, 510, 75, 30);

        removeAllergy.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        removeAllergy.setText("-");
        removeAllergy.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        removeAllergy.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                removeAllergyMouseClicked(evt);
            }
        });
        recordPanel.add(removeAllergy);
        removeAllergy.setBounds(440, 70, 10, 16);

        removeHospitalization.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        removeHospitalization.setText("-");
        removeHospitalization.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        removeHospitalization.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                removeHospitalizationMouseClicked(evt);
            }
        });
        recordPanel.add(removeHospitalization);
        removeHospitalization.setBounds(440, 310, 10, 16);

        removeMedication.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        removeMedication.setText("-");
        removeMedication.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        removeMedication.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                removeMedicationMouseClicked(evt);
            }
        });
        recordPanel.add(removeMedication);
        removeMedication.setBounds(440, 190, 10, 16);

        recordScroll.setViewportView(recordPanel);

        jTabbedPane1.addTab("Record", recordScroll);

        reportPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        reportPanel.setEnabled(false);
        reportPanel.setLayout(null);

        jButton1.setText("Confirm");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        reportPanel.add(jButton1);
        jButton1.setBounds(400, 370, 74, 30);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jScrollPane5.setViewportView(jTextArea1);

        reportPanel.add(jScrollPane5);
        jScrollPane5.setBounds(20, 260, 450, 100);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("Remarks");
        reportPanel.add(jLabel1);
        jLabel1.setBounds(20, 240, 50, 16);

        jTextField1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        reportPanel.add(jTextField1);
        jTextField1.setBounds(100, 60, 370, 22);

        jLabel31.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(102, 102, 102));
        jLabel31.setText("HEENT:");
        reportPanel.add(jLabel31);
        jLabel31.setBounds(20, 60, 70, 20);

        jLabel32.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(102, 102, 102));
        jLabel32.setText("Others:");
        reportPanel.add(jLabel32);
        jLabel32.setBounds(20, 210, 41, 20);

        jLabel33.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(102, 102, 102));
        jLabel33.setText("Extremities:");
        reportPanel.add(jLabel33);
        jLabel33.setBounds(20, 180, 70, 20);

        jLabel34.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(102, 102, 102));
        jLabel34.setText("Abdomen:");
        reportPanel.add(jLabel34);
        jLabel34.setBounds(20, 150, 60, 20);

        jLabel35.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(102, 102, 102));
        jLabel35.setText("Heart:");
        reportPanel.add(jLabel35);
        jLabel35.setBounds(20, 120, 60, 20);

        jLabel36.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(102, 102, 102));
        jLabel36.setText("Chest/Lungs:");
        reportPanel.add(jLabel36);
        jLabel36.setBounds(20, 90, 80, 20);

        jTextField2.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        reportPanel.add(jTextField2);
        jTextField2.setBounds(100, 210, 370, 22);

        jTextField3.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        reportPanel.add(jTextField3);
        jTextField3.setBounds(100, 180, 370, 22);

        jTextField4.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        reportPanel.add(jTextField4);
        jTextField4.setBounds(100, 150, 370, 22);

        jTextField5.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        reportPanel.add(jTextField5);
        jTextField5.setBounds(100, 120, 370, 22);

        jTextField6.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        reportPanel.add(jTextField6);
        jTextField6.setBounds(100, 90, 370, 22);

        jTextField7.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        reportPanel.add(jTextField7);
        jTextField7.setBounds(410, 30, 60, 22);

        jTextField8.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        reportPanel.add(jTextField8);
        jTextField8.setBounds(10, 30, 60, 22);

        jTextField9.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        reportPanel.add(jTextField9);
        jTextField9.setBounds(90, 30, 60, 22);

        jTextField10.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        reportPanel.add(jTextField10);
        jTextField10.setBounds(170, 30, 60, 22);

        jTextField11.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        reportPanel.add(jTextField11);
        jTextField11.setBounds(250, 30, 60, 22);

        jTextField12.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        reportPanel.add(jTextField12);
        jTextField12.setBounds(330, 30, 60, 22);

        jLabel37.setForeground(new java.awt.Color(102, 102, 102));
        jLabel37.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel37.setText("Temp");
        reportPanel.add(jLabel37);
        jLabel37.setBounds(410, 10, 60, 16);

        jLabel38.setForeground(new java.awt.Color(102, 102, 102));
        jLabel38.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel38.setText("Height");
        reportPanel.add(jLabel38);
        jLabel38.setBounds(10, 10, 60, 16);

        jLabel39.setForeground(new java.awt.Color(102, 102, 102));
        jLabel39.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel39.setText("Weight");
        reportPanel.add(jLabel39);
        jLabel39.setBounds(90, 10, 60, 16);

        jLabel40.setForeground(new java.awt.Color(102, 102, 102));
        jLabel40.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel40.setText("BMI");
        reportPanel.add(jLabel40);
        jLabel40.setBounds(170, 10, 60, 16);

        jLabel41.setForeground(new java.awt.Color(102, 102, 102));
        jLabel41.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel41.setText("BP");
        reportPanel.add(jLabel41);
        jLabel41.setBounds(250, 10, 60, 16);

        jLabel42.setForeground(new java.awt.Color(102, 102, 102));
        jLabel42.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel42.setText("PR");
        reportPanel.add(jLabel42);
        jLabel42.setBounds(330, 10, 60, 16);

        jTabbedPane1.addTab("Report", reportPanel);

        historyPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        historyPanel.setLayout(null);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"04/18/2025", null, null, null, "N. Q. Jael", null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Date", "BP", "PR", "Temp", "Staff", ""
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(0).setPreferredWidth(80);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setResizable(false);
            jTable1.getColumnModel().getColumn(3).setResizable(false);
            jTable1.getColumnModel().getColumn(4).setResizable(false);
            jTable1.getColumnModel().getColumn(4).setPreferredWidth(80);
            jTable1.getColumnModel().getColumn(5).setResizable(false);
        }

        historyPanel.add(jScrollPane1);
        jScrollPane1.setBounds(10, 90, 470, 260);

        jLabel28.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel28.setText("History");
        historyPanel.add(jLabel28);
        jLabel28.setBounds(13, 20, 460, 20);

        jButton2.setText("Refresh");
        historyPanel.add(jButton2);
        jButton2.setBounds(400, 53, 80, 30);

        jTabbedPane1.addTab("History", historyPanel);

        getContentPane().add(jTabbedPane1);
        jTabbedPane1.setBounds(0, 280, 560, 420);

        jLabel16.setText("College:");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(390, 130, 60, 16);

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel17.setText(this.student.getStudentCollege());
        getContentPane().add(jLabel17);
        jLabel17.setBounds(460, 130, 40, 16);

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel18.setText(this.student.getStudentCourse());
        getContentPane().add(jLabel18);
        jLabel18.setBounds(460, 110, 80, 16);

        jLabel19.setText("Course:");
        getContentPane().add(jLabel19);
        jLabel19.setBounds(390, 110, 50, 16);

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel20.setText(this.student.getStudentID());
        getContentPane().add(jLabel20);
        jLabel20.setBounds(460, 90, 90, 16);

        jLabel21.setText("Student No.:");
        getContentPane().add(jLabel21);
        jLabel21.setBounds(390, 90, 80, 16);

        jLabel22.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel22.setText(this.student.getStudentAddress());
        getContentPane().add(jLabel22);
        jLabel22.setBounds(80, 230, 470, 16);

        jLabel23.setText("Address:");
        getContentPane().add(jLabel23);
        jLabel23.setBounds(10, 230, 60, 16);

        jLabel24.setText("Contact Person:");
        getContentPane().add(jLabel24);
        jLabel24.setBounds(10, 250, 90, 16);

        jLabel25.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel25.setText(this.student.getStudentcontactPerson());
        getContentPane().add(jLabel25);
        jLabel25.setBounds(110, 250, 210, 16);

        jLabel26.setText("Phone:");
        getContentPane().add(jLabel26);
        jLabel26.setBounds(390, 250, 50, 16);

        jLabel27.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel27.setText(this.student.getStudentPhone());
        getContentPane().add(jLabel27);
        jLabel27.setBounds(440, 250, 90, 16);

        setSize(new java.awt.Dimension(576, 740));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void hasAsthmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hasAsthmaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hasAsthmaActionPerformed

    private void addMedicationsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addMedicationsMouseClicked
        // TODO add your handling code here:
        addRow(this.medicationsTable, this.medicationsTableModel);
    }//GEN-LAST:event_addMedicationsMouseClicked

    private void addAllergyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addAllergyMouseClicked
        // TODO add your handling code here:       
        addRow(this.allergiesTable, this.allergiesTableModel);
    }//GEN-LAST:event_addAllergyMouseClicked

    private void addHospitalizedMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addHospitalizedMouseClicked
        // TODO add your handling code here:
        addRow(this.hospitalizationTable, this.hospitalizationTableModel);
    }//GEN-LAST:event_addHospitalizedMouseClicked

    private void confirmRecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmRecordActionPerformed
        // TODO add your handling code here:    
        if (isEnabled) this.setMedicalRecord();
        this.enableComponents(!isEnabled);
        
        if(this.newRecord) new Thread(() -> {this.entityManager.persist(this.history);}).start() ;
    }//GEN-LAST:event_confirmRecordActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        this.entityManager.getTransaction().commit();
    }//GEN-LAST:event_formWindowClosing

    private void removeAllergyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_removeAllergyMouseClicked
        // TODO add your handling code here:
        this.removeAllergy.setEnabled(this.allergiesTable.getRowCount() < 2);
        if(this.removeAllergy.isEnabled()) this.allergiesTableModel.removeRow(this.allergiesTable.getSelectedRow());
    }//GEN-LAST:event_removeAllergyMouseClicked

    private void removeMedicationMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_removeMedicationMouseClicked
        // TODO add your handling code here:
        this.removeMedication.setEnabled(this.medicationsTable.getRowCount() < 2);
        if(this.removeMedication.isEnabled()) this.medicationsTableModel.removeRow(this.medicationsTable.getSelectedRow());
    }//GEN-LAST:event_removeMedicationMouseClicked

    private void removeHospitalizationMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_removeHospitalizationMouseClicked
        // TODO add your handling code here:
        this.removeHospitalization.setEnabled(this.hospitalizationTable.getRowCount() < 2);
        if(this.removeHospitalization.isEnabled()) this.hospitalizationTableModel.removeRow(this.hospitalizationTable.getSelectedRow());
    }//GEN-LAST:event_removeHospitalizationMouseClicked

    private void addRow(JTable table, DefaultTableModel model) {
        if (!table.getValueAt(table.getRowCount() - 1, 0).toString().isBlank() && this.isEnabled) model.addRow(new Object[]{""});
    }
    
    private boolean enableComponents(Boolean flag) {
        this.isEnabled = flag;
        this.hasAsthma.setEnabled(flag);
        this.hasEpilipsy.setEnabled(flag);
        this.hasHermia.setEnabled(flag);
        this.hasHeartDiseas.setEnabled(flag);
                
        this.allergiesTable.setEnabled(flag);
        this.medicationsTable.setEnabled(flag);
        this.hospitalizationTable.setEnabled(flag);
        this.addAllergy.setEnabled(flag);
        this.removeAllergy.setEnabled(flag);
        this.addMedications.setEnabled(flag);
        this.removeMedication.setEnabled(flag);
        this.addHospitalized.setEnabled(flag);
        this.removeHospitalization.setEnabled(flag);
        
        this.lmpDate.setEnabled(flag && this.student.getStudentSex().equalsIgnoreCase("female"));
        
        this.confirmRecord.setText(flag ? "Confirm" : "Edit");
        
        return flag;
    }
    
    private void updateDisplay() {
        LocalDate createdDate = this.history.getDateTaken()
                .toInstant()
                .atZone(ZoneId.systemDefault())
                .toLocalDate();
        this.dateCreated.setText(createdDate.format(this.defaultDateFormat));
        this.hasAsthma.setSelected(this.history.getHasAsthma());
        this.hasEpilipsy.setSelected(this.history.getHasEpilepsy());
        this.hasHermia.setSelected(this.history.getHasHermia());
        this.hasHeartDiseas.setSelected(this.history.getHasheartDisease());

        this.allergies = Arrays.asList(this.history.getAllergies().split(","));
        this.medications = Arrays.asList(this.history.getMedications().split(","));
        this.hospitalizations = Arrays.asList(this.history.getSurgery().split(","));
        setData(this.allergiesTable, this.allergies);
        setData(this.medicationsTable, this.medications);
        setData(this.hospitalizationTable, this.hospitalizations);
        
        if (this.history.getLmp() != null) this.dateChooser.setSelectedDate(this.history.getLmp());
    }
    
    private void setMedicalRecord() {
        this.history.setDateTaken(dateTaken);
        this.history.setHasAsthma(this.hasAsthma.isSelected());
        this.history.setHasEpilepsy(this.hasEpilipsy.isSelected());
        this.history.setHasHermia(this.hasHermia.isSelected());
        this.history.setHasheartDisease(this.hasHeartDiseas.isSelected());
        
        
        
        this.history.setAllergies(this.joinValues(this.allergiesTable));
        this.history.setMedications(this.joinValues(this.medicationsTable));
        this.history.setSurgery(this.joinValues(this.hospitalizationTable));
        
        this.history.setLmp(this.lmpDate.getDate());
        
        this.history.setStudentID(student);
    }
    
    private String joinValues(JTable table) {
        StringBuilder sb = new StringBuilder();
            for (int i = 0; i < table.getRowCount(); i++) {
                String val = table.getValueAt(i, 0).toString();
                if (!val.isBlank()) {
                    if (i > 0) sb.append(", ");
                    sb.append(val);
                }
            }
        return sb.toString();
    }
    
    private void setData(JTable table, List data) {
        for (int i = 0; i <= data.size() - 1; i++) {
            table.setValueAt(data.get(i), i, 0);
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentRecord().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addAllergy;
    private javax.swing.JLabel addHospitalized;
    private javax.swing.JLabel addMedications;
    private javax.swing.JTable allergiesTable;
    private javax.swing.JButton confirmRecord;
    private com.raven.datechooser.DateChooser dateChooser;
    private javax.swing.JLabel dateCreated;
    private javax.swing.JPanel femaleOnlyPanel;
    private javax.swing.JCheckBox hasAsthma;
    private javax.swing.JCheckBox hasEpilipsy;
    private javax.swing.JCheckBox hasHeartDiseas;
    private javax.swing.JCheckBox hasHermia;
    private javax.swing.JPanel historyPanel;
    private javax.swing.JTable hospitalizationTable;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private com.toedter.calendar.JDateChooser lmpDate;
    private javax.swing.JTable medicationsTable;
    private javax.swing.JPanel recordPanel;
    private javax.swing.JScrollPane recordScroll;
    private javax.swing.JLabel removeAllergy;
    private javax.swing.JLabel removeHospitalization;
    private javax.swing.JLabel removeMedication;
    private javax.swing.JPanel reportPanel;
    // End of variables declaration//GEN-END:variables

}
